version: '3.8'

services:
  graph-node:
    image: graphprotocol/graph-node:v0.35.1
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8020:8020'
      - '8030:8030'
      - '8040:8040'
    depends_on:
      - ipfs
    restart: unless-stopped
    environment:
      # Remote PostgreSQL connection
      postgres_host: finmates.com
      postgres_port: 5432
      postgres_user: user
      postgres_pass: ${POSTGRES_PASSWORD}  # Set in .env file
      postgres_db: stock-data  # or create a new database for graph-node

      # IPFS configuration
      ipfs: 'ipfs:5001'

      # Alchemy RPC endpoint
      ethereum: 'arbitrum-one:https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}'

      # Graph Node settings
      GRAPH_LOG: info
      GRAPH_ETHEREUM_CLEANUP_BLOCKS: 'true'
      GRAPH_ALLOW_NON_DETERMINISTIC_IPFS: 'true'

      # Optimizations for Alchemy
      GRAPH_ETHEREUM_POLLING_INTERVAL: '1000'
      GRAPH_ETHEREUM_REQUEST_RETRIES: '15'
      GRAPH_ETHEREUM_BLOCK_BATCH_SIZE: '10'
      GRAPH_ETHEREUM_RPC_MAX_PARALLEL_REQUESTS: '10'
      GRAPH_ETHEREUM_TRACE_STREAM_STEP_SIZE: '50'
      GRAPH_ETHEREUM_JSON_RPC_TIMEOUT: '60'
      GRAPH_ETHEREUM_MAX_BLOCK_RANGE_SIZE: '1000'
      GRAPH_ETHEREUM_GENESIS_BLOCK_NUMBER: '200000000'

      # GraphQL settings
      GRAPH_GRAPHQL_MAX_FIRST: '1000'
      GRAPH_GRAPHQL_MAX_SKIP: '1000'
      GRAPH_ALLOW_NON_DETERMINISTIC_FULLTEXT_SEARCH: 'true'

      # PostgreSQL connection pool
      GRAPH_STORE_CONNECTION_POOL_SIZE: '10'
      DATABASE_URL: 'postgresql://user:${POSTGRES_PASSWORD}@finmates.com:5432/stock-data'

    volumes:
      - ./data/graph-node:/data
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '3'
        reservations:
          memory: 4G
          cpus: '2'

  ipfs:
    image: ipfs/kubo:v0.24.0
    ports:
      - '5001:5001'
      - '8080:8080'
    restart: unless-stopped
    environment:
      IPFS_PROFILE: server
      IPFS_PATH: /data/ipfs
    volumes:
      - ./data/ipfs:/data/ipfs
    command: ["daemon", "--migrate=true", "--enable-gc", "--routing=none"]
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'

  # No local postgres needed!